# Generated by Django 4.2 on 2026-01-18 09:42

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_prefs_and_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealreceipt',
            name='date',
            field=models.DateField(default=users.models._today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=users.models._today, verbose_name='Дата начала'),
        ),
    ]
