# Generated by Django 4.2 on 2026-01-18 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_mealreceipt_date_alter_subscription_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пополнение баланса',
                'verbose_name_plural': 'Пополнения баланса',
                'ordering': ['-created_at'],
            },
        ),
    ]
