# Generated by Django 4.2 on 2026-01-25 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_balancetopup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealreceipt',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.RemoveField(
            model_name='mealreceipt',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='period',
        ),
        migrations.AddField(
            model_name='mealreceipt',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mealreceipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mealreceipt',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mealreceipt',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mealreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('breakfast', 'Только завтраки'), ('lunch', 'Только обеды'), ('both', 'Завтрак + обед')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
