# Generated by Django 4.2 on 2026-01-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_mealreceipt_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('breakfast', 'Завтраки'), ('lunch', 'Обеды')], max_length=20),
        ),
    ]
