# Generated by Django 4.2 on 2026-02-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_mealrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrequest',
            name='stock_deducted',
            field=models.BooleanField(default=False, verbose_name='Продукты списаны'),
        ),
    ]
