# Generated by Django 4.2 on 2026-02-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_organization_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealreceipt',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Утро'), ('lunch', 'День')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mealrequest',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Утро'), ('lunch', 'День')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mealrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Запрошено'), ('issued', 'Выдано поваром'), ('confirmed', 'Подтверждено участником'), ('cancelled', 'Отменено')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('breakfast', 'Утро'), ('lunch', 'День')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Участник'), ('cook', 'Производство'), ('admin', 'Eco-менеджер')], default='student', max_length=20, verbose_name='Роль'),
        ),
    ]
