# Generated by Django 4.2 on 2026-02-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_mealreceipt_meal_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealreceipt',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='mealrequest',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.AlterField(
            model_name='mealreceipt',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mealrequest',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mealrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Запрошено'), ('issued', 'Выдано поваром'), ('confirmed', 'Подтверждено учеником'), ('cancelled', 'Отменено')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('breakfast', 'Завтраки'), ('lunch', 'Обеды')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('cook', 'Повар'), ('admin', 'Администратор')], default='student', max_length=20, verbose_name='Роль'),
        ),
    ]
