# Generated by Django 4.2 on 2026-02-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_mealreceipt_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Клиент'), ('cook', 'Шеф / кухня'), ('admin', 'Менеджер кейтеринга')], default='student', max_length=20),
        ),
    ]
