# Generated by Django 4.2 on 2026-02-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_and_purchase_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='goals',
            field=models.CharField(blank=True, max_length=300, verbose_name='Цели (через запятую)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название заведения'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('school', 'Школа/университет'), ('office', 'Офис/корпоративное питание'), ('cafe', 'Кафе/столовая/ресторан'), ('catering', 'Кейтеринг/мероприятия'), ('retail', 'Магазин/кулинария'), ('ngo', 'НКО/социальная кухня'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип заведения'),
        ),
    ]
