# Generated by Django 4.2 on 2026-02-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Закуплено'), ('cancelled', 'Отменено'), ('rejected', 'Отклонено')], default='new', max_length=20),
        ),
    ]
