# Generated by Django 4.2 on 2026-02-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_alter_dailymenu_options_alter_product_options_and_more'),
        ('users', '0012_remove_mealreceipt_organization_and_more'),
        ('core', '0003_alter_organization_goals_alter_organization_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
