# Generated by Django 4.2 on 2026-02-09 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem', verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='menu.OrderItem', to='menu.menuitem', verbose_name='Позиции'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='menu.product'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='breakfast_items',
            field=models.ManyToManyField(blank=True, related_name='daily_breakfasts', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='lunch_items',
            field=models.ManyToManyField(blank=True, related_name='daily_lunches', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='banquetmenu',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banquet_menus_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='banquetmenu',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='banquet_menus', to='menu.menuitem', verbose_name='Блюда'),
        ),
        migrations.AddField(
            model_name='banquetmenu',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banquet_menus_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemingredient',
            unique_together={('item', 'product')},
        ),
    ]
