# Generated by Django 4.2 on 2026-01-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_add_more_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(default='г', max_length=20)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='allergens',
            field=models.CharField(blank=True, max_length=300, verbose_name='Аллергены (коды через пробел)'),
        ),
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.menuitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='menu.product')),
            ],
            options={
                'unique_together': {('item', 'product')},
            },
        ),
    ]
