# Generated by Django 4.2 on 2026-01-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_product_alter_menuitem_allergens_menuitemingredient'),
        ('menu', '0006_recipes_and_ingredients'),
    ]

    operations = [
    ]
