# Generated by Django 4.2 on 2026-02-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_normalize_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('breakfast_items', models.ManyToManyField(blank=True, related_name='daily_breakfasts', to='menu.menuitem')),
                ('lunch_items', models.ManyToManyField(blank=True, related_name='daily_lunches', to='menu.menuitem')),
            ],
        ),
    ]
