# Generated by Django 4.2 on 2026-02-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_organization_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymenu',
            options={'verbose_name': 'План питания', 'verbose_name_plural': 'Планы питания'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
