# Generated by Django 4.2 on 2026-02-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_dailymenu_options_alter_product_options_and_more'),
        ('menu', '0014_planned_portions'),
    ]

    operations = [
    ]
