# Generated by Django 4.2 on 2026-02-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_order_banquet_fields'),
        ('menu', '0015_merge_20260207_2121'),
    ]

    operations = [
    ]
