# Generated by Django 4.2 on 2026-02-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_rename_categories_for_catering'),
        ('menu', '0016_merge_20260209_1325'),
    ]

    operations = [
    ]
