# Generated by Django 4.2 on 2026-02-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_merge_20260209_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymenu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='dailymenu',
            name='uniq_dailymenu_org_date',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_product_org_name',
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='planned_breakfast_portions',
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='planned_lunch_portions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='organization',
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
