# Generated by Django 4.2 on 2026-02-09 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0018_alter_dailymenu_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetmenu',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banquet_menus_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='banquetmenu',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Проверено'),
        ),
        migrations.AddField(
            model_name='banquetmenu',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banquet_menus_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='banquetmenu',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='banquetmenu',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
    ]
